# Generated by Django 5.1 on 2024-09-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servise',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='service_icon/', verbose_name='Икона'),
        ),
        migrations.AddField(
            model_name='servisetranslation',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='servisetranslation',
            name='short_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое название'),
        ),
    ]
