# Generated by Django 5.1 on 2024-09-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0003_advantages_advantagestranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servisetranslation',
            name='description',
        ),
    ]
