# Generated by Django 5.1 on 2024-09-02 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0004_remove_servisetranslation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='faject.category', verbose_name='Категория'),
        ),
    ]
