# Generated by Django 5.1 on 2024-09-02 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0005_alter_servise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='faject.category', verbose_name='Категория'),
        ),
    ]
