# Generated by Django 5.1 on 2024-08-21 12:21

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0005_servise_servisetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servisetranslation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
    ]
