# Generated by Django 5.1 on 2024-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0007_servicedesctiption_servicedesctiptiontranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servise',
            name='image',
            field=models.FileField(upload_to='service/', verbose_name='Изображение'),
        ),
    ]
