# Generated by Django 5.1 on 2024-09-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0008_alter_servise_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedesctiption',
            options={'ordering': ['id'], 'verbose_name': 'Описание услуги', 'verbose_name_plural': 'Описание услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicedesctiptiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Описание услуги Translation'},
        ),
        migrations.AlterField(
            model_name='servicedesctiption',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='faject.servise', verbose_name='Услуга'),
        ),
    ]
