# Generated by Django 5.1 on 2024-09-02 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0009_alter_servicedesctiption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faject.category', verbose_name='Категория услуг'),
        ),
    ]
