# Generated by Django 5.1 on 2024-08-22 05:11

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0010_blogcategory_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comanda/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
                'ordering': ['-id'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='tools', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Инструменты',
                'verbose_name_plural': 'Инструменты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ToolsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Инструменты Категория',
                'verbose_name_plural': 'Инструменты Категория',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AlterModelOptions(
            name='blogtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Блог Translation'},
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('phone', models.CharField(max_length=250, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('description', models.TextField(verbose_name='Опишите свой проект')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faject.subcategory', verbose_name='Услугу')),
            ],
            options={
                'verbose_name': 'ОСТАВЬТЕ ЗАЯВКУ',
                'verbose_name_plural': 'ОСТАВЬТЕ ЗАЯВКУ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ComandaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=250, verbose_name='Ф.И.О')),
                ('position', models.CharField(max_length=250, verbose_name='Позиция')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='faject.comanda')),
            ],
            options={
                'verbose_name': 'Команда Translation',
                'db_table': 'faject_comanda_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
