# Generated by Django 5.1 on 2024-08-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0011_comanda_tools_toolscategory_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faject.toolscategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
