# Generated by Django 5.1 on 2024-08-24 08:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faject', '0012_tools_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstranslation',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
